#!/usr/bin/env bash
#
# measure.sh — regenerate MEASUREMENTS.md, the single source of truth for every
# number this curriculum quotes about the reference harness.
#
# Why this exists: the published figures went stale TWICE without anyone
# noticing, because adding a tool in one pass silently changed the tools block
# and therefore every token count in four chapters. Prose cannot be trusted to
# track code. Run this after any change to harness.ts, then
# `bin/check-numbers.sh` to confirm the docs agree.

set -uo pipefail
cd "$(dirname "$0")"
field() { echo "$1" | grep -oE "$2" | grep -oE '[0-9]+' | head -1; }
run() { rm -rf .state; env "$@" node harness.ts 2>&1; }

declare -A RAW BILL HIT CMP RST
for p in none compact clear full reset; do
  o=$(run POLICY=$p SCRIPT=long)
  RAW[$p]=$(field "$o" '[0-9]+ tokens\)')
  BILL[$p]=$(field "$o" 'billed: [0-9]+')
  HIT[$p]=$(field "$o" '\([0-9]+% hit')
  CMP[$p]=$(field "$o" 'compactions: [0-9]+')
  RST[$p]=$(field "$o" 'resets: [0-9]+')
done
dyn=$(run SCRIPT=long);           dyn_calls=$(field "$dyn" 'model calls: [0-9]+'); dyn_raw=$(field "$dyn" '[0-9]+ tokens\)')
rtd=$(run ROUTER=on SCRIPT=long); rtd_calls=$(field "$rtd" 'model calls: [0-9]+'); rtd_raw=$(field "$rtd" '[0-9]+ tokens\)')
tools=$(field "$dyn" '^  tools +[0-9]+')
[ -z "$tools" ] && tools=$(echo "$dyn" | awk '/^  tools/{print $2}')
window=400
pct=$(( tools * 100 / window ))
nassert=$(./verify.sh --json 2>/dev/null | node -pe 'JSON.parse(require("fs").readFileSync(0,"utf8")).pass' 2>/dev/null)
rm -rf .state

cat > MEASUREMENTS.md <<EOF
# Measurements

**Generated by \`measure.sh\` — do not hand-edit.** Every number the chapters quote
about the reference harness comes from here. Regenerate after any change to
\`harness.ts\`, then run \`bin/check-numbers.sh\` to confirm the prose agrees.

This file exists because the published figures went stale twice: adding a tool in
a later pass changed the tools block and silently invalidated token counts in four
chapters. Prose does not track code on its own.

## Context policies (\`SCRIPT=long\`, 20 steps, 400-token window)

| Policy | Compactions | Cache hit | Raw tokens | Billed |
|---|---|---|---|---|
| none | ${CMP[none]} | ${HIT[none]}% | ${RAW[none]} | ${BILL[none]} |
| compact | ${CMP[compact]} | ${HIT[compact]}% | ${RAW[compact]} | ${BILL[compact]} |
| clear | ${CMP[clear]} | ${HIT[clear]}% | ${RAW[clear]} | ${BILL[clear]} |
| full | ${CMP[full]} | ${HIT[full]}% | ${RAW[full]} | ${BILL[full]} |
| reset | ${RST[reset]} resets | ${HIT[reset]}% | ${RAW[reset]} | ${BILL[reset]} |

The finding (Ch.4, Ch.7): \`clear\` uses fewer **raw** tokens than \`compact\` and
costs more **billed**. The ranking inverts depending on which column you optimise.

\`reset\` (Ch.10) is measured here for **cost only**. Ch.10's argument for resetting
is that it prevents context anxiety — losing coherence as the window fills — and
this harness's model is a deterministic script that cannot exhibit that failure.
So this table shows what reset costs and says nothing about what it buys.

## Static routing (Ch.3)

| | Model calls | Raw tokens |
|---|---|---|
| all dynamic | ${dyn_calls} | ${dyn_raw} |
| \`ROUTER=on\` | ${rtd_calls} | ${rtd_raw} |

## Fixed tool cost (Ch.5)

Tool definitions: **${tools} tokens** of a ${window}-token window = **${pct}%**
spent before any work happens.

## Test suite

\`verify.sh\`: **${nassert} assertions**, checked against \`baseline.json\`.
EOF
echo "wrote MEASUREMENTS.md"
cat MEASUREMENTS.md | tail -25
